services:
  mongos-router:
    container_name: mongos-router
    image: dh-mirror.gitverse.ru/mongo:8.2.3-noble
    restart: always
    ports:
      - "27016:27016"
    networks:
      - app-network
    volumes:
      - router-data:/data/db
    command:
      [
        "mongos",
        "--configdb",
        "config_server/config-server:27017",
        "--bind_ip_all",
        "--port",
        "27016"
      ]
    healthcheck:
      test: [ "CMD", "mongosh", "--port", "27016", "--eval", "db.adminCommand('ping')" ]
      interval: 5s
      start_period: 10s

  config-server:
    container_name: config-server
    image: dh-mirror.gitverse.ru/mongo:8.2.3-noble
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - config-data:/data/db
    networks:
      - app-network
    command:
      [
        "--configsvr",
        "--replSet",
        "config_server",
        "--bind_ip_all",
        "--port",
        "27017"
      ]
    healthcheck:
      test: [ "CMD", "mongosh", "--eval", "db.adminCommand('ping')" ]
      interval: 5s
      start_period: 10s

  shard1:
    container_name: shard1
    image: dh-mirror.gitverse.ru/mongo:8.2.3-noble
    restart: always
    ports:
      - "27018:27018"
    networks:
      - app-network
    volumes:
      - shard1-data:/data/db
    command:
      [
        "--shardsvr",
        "--replSet",
        "shard1",
        "--bind_ip_all",
        "--port",
        "27018"
      ]
    healthcheck:
      test: [ "CMD", "mongosh", "--port", "27018", "--eval", "db.adminCommand('ping')" ]
      interval: 5s
      start_period: 10s

  shard2:
    container_name: shard2
    image: dh-mirror.gitverse.ru/mongo:8.2.3-noble
    restart: always
    ports:
      - "27019:27019"
    networks:
      - app-network
    volumes:
      - shard2-data:/data/db
    command:
      [
        "--shardsvr",
        "--replSet",
        "shard2",
        "--bind_ip_all",
        "--port",
        "27019"
      ]
    healthcheck:
      test: [ "CMD", "mongosh", "--port", "27019", "--eval", "db.adminCommand('ping')" ]
      interval: 5s
      start_period: 10s

  cluster-init:
    container_name: cluster-init
    image: dh-mirror.gitverse.ru/mongo:8.2.3-noble
    networks:
      - app-network
    volumes:
      - ./init-cluster.sh:/init-cluster.sh
    entrypoint: ["/bin/bash", "/init-cluster.sh"]
    depends_on:
      - config-server
      - shard1
      - shard2
      - mongos-router

  pymongo-api:
    container_name: pymongo-api
    build:
      context: api_app
      dockerfile: Dockerfile
    depends_on:
      - mongos-router
    ports:
      - "8080:8080"
    environment:
      MONGODB_URL: "mongodb://mongos-router:27016"
      MONGODB_DATABASE_NAME: "somedb"
    networks:
      - app-network

networks:
  app-network:

volumes:
  router-data:
  config-data:
  shard1-data:
  shard2-data:
